// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatus } from "./AgentStatus";
import type { SessionId } from "./SessionId";

export type CollabAgentSpawnEndEvent = { 
/**
 * Identifier for the collab tool call.
 */
call_id: string, 
/**
 * Session ID of the sender.
 */
sender_session_id: SessionId, 
/**
 * Session ID of the newly spawned agent, if it was created.
 */
new_session_id: SessionId | null, 
/**
 * Initial prompt sent to the agent. Can be empty to prevent CoT leaking at the
 * beginning.
 */
prompt: string, 
/**
 * Last known status of the new agent reported to the sender agent.
 */
status: AgentStatus, };
