// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatus } from "./AgentStatus";
import type { SessionId } from "./SessionId";

export type CollabCloseEndEvent = { 
/**
 * Identifier for the collab tool call.
 */
call_id: string, 
/**
 * Session ID of the sender.
 */
sender_session_id: SessionId, 
/**
 * Session ID of the receiver.
 */
receiver_session_id: SessionId, 
/**
 * Last known status of the receiver agent reported to the sender agent before
 * the close.
 */
status: AgentStatus, };
