// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";

export type CollabAgentInteractionBeginEvent = { 
/**
 * Identifier for the collab tool call.
 */
call_id: string, 
/**
 * Session ID of the sender.
 */
sender_session_id: SessionId, 
/**
 * Session ID of the receiver.
 */
receiver_session_id: SessionId, 
/**
 * Prompt sent from the sender to the receiver. Can be empty to prevent CoT
 * leaking at the beginning.
 */
prompt: string, };
