// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";

export type CollabCloseBeginEvent = { 
/**
 * Identifier for the collab tool call.
 */
call_id: string, 
/**
 * Thread ID of the sender.
 */
sender_thread_id: SessionId, 
/**
 * Thread ID of the receiver.
 */
receiver_thread_id: SessionId, };
