// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatus } from "./AgentStatus";
import type { SessionId } from "./SessionId";

export type CollabWaitingEndEvent = { 
/**
 * Session ID of the sender.
 */
sender_session_id: SessionId, 
/**
 * ID of the waiting call.
 */
call_id: string, 
/**
 * Last known status of the receiver agents reported to the sender agent.
 */
statuses: { [key in SessionId]?: AgentStatus }, };
