// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavfoxErrorInfo } from "./SavfoxErrorInfo";

export type ErrorEvent = { message: string, savfox_error_info: SavfoxErrorInfo | null, };
