// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventMsg } from "./EventMsg";
import type { SessionId } from "./SessionId";

export type ForkConversationResponse = { conversationId: SessionId, model: string, initialMessages: Array<EventMsg> | null, rolloutPath: string, };
