// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewConversationParams } from "./NewConversationParams";
import type { SessionId } from "./SessionId";

export type ForkConversationParams = { path: string | null, conversationId: SessionId | null, overrides: NewConversationParams | null, };
