// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";
import type { TurnItem } from "./TurnItem";

export type ItemStartedEvent = { session_id: SessionId, turn_id: string, item: TurnItem, };
