// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReasoningContentDeltaEvent = { session_id: string, turn_id: string, item_id: string, delta: string, summary_index: bigint, };
