// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputItem } from "./InputItem";
import type { SessionId } from "./SessionId";

export type SendUserMessageParams = { conversationId: SessionId, items: Array<InputItem>, };
