// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";

export type SubAgentSource = "review" | "compact" | { "session_spawn": { parent_session_id: SessionId, depth: number, } } | { "other": string };
