use std::collections::HashMap;
use std::ffi::OsStr;
use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use clap::Parser;
use owo_colors::OwoColorize;
use savfox_core::config::{CONFIG_TOML_FILE, find_savfox_home};
use savfox_gateway_server::config::{Severity, validate_config};
use serde::{Deserialize, Serialize};

/// Diagnose system health and configuration.
#[derive(Debug, Parser)]
pub struct DoctorCommand {
    /// Check network connectivity to LLM providers.
    #[clap(long, default_value_t = true)]
    pub network: bool,

    /// Savfox home directory override.
    #[clap(long)]
    pub savfox_home: Option<PathBuf>,

    /// Auto-repair common issues when possible.
    #[clap(long)]
    pub yes: bool,
}

#[derive(Default)]
struct DoctorSummary {
    ok: u32,
    warn: u32,
    fail: u32,
    suggestions: Vec<String>,
    repaired: Vec<String>,
}

impl DoctorSummary {
    fn ok(&mut self, label: &str, detail: &str) {
        println!("  {} {}: {}", "[OK]".green(), label, detail);
        self.ok = self.ok.saturating_add(1);
    }

    fn warn(&mut self, label: &str, detail: &str) {
        println!("  {} {}: {}", "[WARN]".yellow(), label, detail);
        self.warn = self.warn.saturating_add(1);
    }

    fn fail(&mut self, label: &str, detail: &str) {
        println!("  {} {}: {}", "[FAIL]".red(), label, detail);
        self.fail = self.fail.saturating_add(1);
    }

    fn suggest(&mut self, command: impl Into<String>) {
        let command = command.into();
        if !self.suggestions.iter().any(|s| s == &command) {
            self.suggestions.push(command);
        }
    }

    fn repaired(&mut self, item: impl Into<String>) {
        self.repaired.push(item.into());
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct StoredAuthProfile {
    id: String,
    api_key: String,
    #[serde(default)]
    usage_tokens: u64,
    #[serde(default)]
    usage_cost_usd: f64,
    #[serde(default)]
    cooldown_until: Option<u64>,
    #[serde(default)]
    last_error: Option<String>,
}

const PERMANENT_FAILURE_SENTINEL: u64 = u64::MAX;

// ---------------------------------------------------------------------------
// Individual checks
// ---------------------------------------------------------------------------

fn check_build_info(summary: &mut DoctorSummary) {
    println!();
    println!("{}", "Build Info".bold());
    println!("{}", "----------".bold());
    summary.ok("Version", env!("CARGO_PKG_VERSION"));
    summary.ok(
        "Target",
        &format!("{}-{}", std::env::consts::ARCH, std::env::consts::OS),
    );
    summary.ok("OS", std::env::consts::OS);
    summary.ok("Arch", std::env::consts::ARCH);
}

fn check_config_integrity(savfox_home: &Path, auto_repair: bool, summary: &mut DoctorSummary) {
    println!();
    println!("{}", "Configuration".bold());
    println!("{}", "-------------".bold());

    let config_path = savfox_home.join(CONFIG_TOML_FILE);
    if !config_path.exists() {
        summary.warn(
            "Config file",
            &format!("{} (not found)", config_path.display()),
        );
        summary.suggest("savfox wizard");
        if auto_repair {
            if let Err(err) = std::fs::write(
                &config_path,
                "# Generated by `savfox doctor --yes`\n# Fill in provider and channel settings.\n",
            ) {
                summary.fail(
                    "Auto-repair",
                    &format!("failed to create config.toml: {err}"),
                );
            } else {
                summary.repaired(format!("created {}", config_path.display()));
                summary.ok("Auto-repair", &format!("created {}", config_path.display()));
            }
        }
        return;
    }

    let contents = match std::fs::read_to_string(&config_path) {
        Ok(c) => c,
        Err(e) => {
            summary.fail(
                "Config file",
                &format!("{} (read error: {})", config_path.display(), e),
            );
            summary.suggest("savfox config validate");
            return;
        }
    };

    let toml_value = match contents.parse::<toml::Value>() {
        Ok(value) => {
            summary.ok(
                "Config parse",
                &format!("{} (valid TOML)", config_path.display()),
            );
            value
        }
        Err(e) => {
            summary.fail(
                "Config parse",
                &format!("{} (parse error: {})", config_path.display(), e),
            );
            summary.suggest("savfox config validate");
            return;
        }
    };

    let json_value = match serde_json::to_value(toml_value) {
        Ok(value) => value,
        Err(e) => {
            summary.fail(
                "Config schema",
                &format!("TOML to JSON conversion failed: {e}"),
            );
            summary.suggest("savfox config validate");
            return;
        }
    };

    let validation = validate_config(&json_value);
    let error_count = validation
        .errors
        .iter()
        .filter(|e| matches!(e.severity, Severity::Error))
        .count();
    let warning_count = validation
        .errors
        .iter()
        .filter(|e| matches!(e.severity, Severity::Warning))
        .count();

    if error_count == 0 && warning_count == 0 {
        summary.ok("Config schema", "no validation issues");
    } else {
        if error_count > 0 {
            summary.fail(
                "Config schema",
                &format!("{error_count} error(s), {warning_count} warning(s)"),
            );
            summary.suggest("savfox config validate");
        } else {
            summary.warn(
                "Config schema",
                &format!("{warning_count} warning(s), no hard errors"),
            );
        }

        for issue in validation.errors.iter().take(8) {
            match issue.severity {
                Severity::Error => {
                    summary.fail("  schema", &format!("{}: {}", issue.field, issue.message))
                }
                Severity::Warning => {
                    summary.warn("  schema", &format!("{}: {}", issue.field, issue.message))
                }
            }
        }
    }

    summary.ok("Savfox home", &format!("{}", savfox_home.display()));
}

/// Describes a binary to look for on the PATH.
struct BinCheck {
    label: &'static str,
    candidates: &'static [&'static str],
    required: bool,
    purpose: &'static str,
}

fn check_dependencies(summary: &mut DoctorSummary) {
    println!();
    println!("{}", "Dependencies".bold());
    println!("{}", "------------".bold());

    let bins = [
        BinCheck {
            label: "git",
            candidates: &["git"],
            required: true,
            purpose: "version control",
        },
        BinCheck {
            label: "node",
            candidates: &["node"],
            required: false,
            purpose: "MCP servers",
        },
        BinCheck {
            label: "docker",
            candidates: &["docker"],
            required: false,
            purpose: "sandbox containers",
        },
        BinCheck {
            label: "ffmpeg",
            candidates: &["ffmpeg"],
            required: false,
            purpose: "media/audio processing",
        },
        BinCheck {
            label: "signal-cli",
            candidates: &["signal-cli"],
            required: false,
            purpose: "Signal channel",
        },
        BinCheck {
            label: "chrome",
            candidates: &["google-chrome", "chromium", "chrome", "msedge"],
            required: false,
            purpose: "browser automation",
        },
    ];

    for bin in &bins {
        let mut found_path = None;
        for candidate in bin.candidates {
            if let Ok(path) = which::which(candidate) {
                found_path = Some(path);
                break;
            }
        }

        match found_path {
            Some(path) => summary.ok(bin.label, &format!("{} ({})", path.display(), bin.purpose)),
            None if bin.required => {
                summary.fail(bin.label, &format!("not found on PATH ({})", bin.purpose));
                summary.suggest(format!("Install {}", bin.label));
            }
            None => summary.warn(
                bin.label,
                &format!("not found on PATH (optional, for {})", bin.purpose),
            ),
        }
    }
}

fn check_environment_setup(savfox_home: &Path, summary: &mut DoctorSummary) {
    println!();
    println!("{}", "Environment".bold());
    println!("{}", "-----------".bold());

    let path_var = std::env::var_os("PATH");
    let path_has_home = path_var
        .as_deref()
        .is_some_and(|v| path_contains(v, savfox_home));
    if path_has_home {
        summary.ok("PATH", "contains savfox home path");
    } else {
        summary.warn("PATH", "does not contain savfox home path");
        summary.suggest("Add Savfox install path to PATH");
    }

    let completion_paths = completion_paths();
    let installed: Vec<PathBuf> = completion_paths
        .into_iter()
        .filter(|path| path.exists())
        .collect();
    if installed.is_empty() {
        summary.warn("Completions", "no shell completion file detected");
        summary.suggest("savfox completion <bash|zsh|fish|powershell> > <completion-file>");
    } else {
        let list = installed
            .iter()
            .map(|p| p.display().to_string())
            .collect::<Vec<_>>()
            .join(", ");
        summary.ok("Completions", &list);
    }
}

fn check_state_dirs(savfox_home: &Path, auto_repair: bool, summary: &mut DoctorSummary) {
    println!();
    println!("{}", "State Directory".bold());
    println!("{}", "---------------".bold());

    let required_dirs = [
        savfox_home.to_path_buf(),
        savfox_home.join("sessions"),
        savfox_home.join("gateway"),
        savfox_home.join("logs"),
        savfox_home.join("auth"),
    ];

    for dir in required_dirs {
        if dir.exists() {
            summary.ok("Dir", &format!("{} (exists)", dir.display()));
        } else if auto_repair {
            match std::fs::create_dir_all(&dir) {
                Ok(()) => {
                    summary.ok("Dir", &format!("{} (created)", dir.display()));
                    summary.repaired(format!("created directory {}", dir.display()));
                }
                Err(err) => {
                    summary.fail("Dir", &format!("{} (create failed: {err})", dir.display()));
                    summary.suggest(format!("Create directory {}", dir.display()));
                }
            }
        } else {
            summary.warn("Dir", &format!("{} (missing)", dir.display()));
            summary.suggest(format!("mkdir -p {}", dir.display()));
        }
    }

    let write_test_path = savfox_home.join(".doctor_write_test");
    match std::fs::write(&write_test_path, b"ok") {
        Ok(()) => {
            let _ = std::fs::remove_file(&write_test_path);
            summary.ok("Permissions", "state directory is writable");
        }
        Err(err) => {
            summary.fail(
                "Permissions",
                &format!("cannot write in savfox home: {err}"),
            );
            summary.suggest("Fix file permissions for Savfox state directory");
        }
    }
}

fn check_web_ui_assets(savfox_home: &Path, summary: &mut DoctorSummary) {
    println!();
    println!("{}", "Web UI Assets".bold());
    println!("{}", "-------------".bold());

    let mut candidates = vec![
        savfox_home.join("web").join("index.html"),
        PathBuf::from("crates/gateway-dioxus/dist/index.html"),
        PathBuf::from("crates/gateway-dioxus/index.html"),
    ];
    if let Ok(exe) = std::env::current_exe() {
        if let Some(parent) = exe.parent() {
            candidates.push(parent.join("web").join("index.html"));
        }
    }

    if let Some(path) = candidates.into_iter().find(|p| p.exists()) {
        summary.ok("Web assets", &format!("found {}", path.display()));
    } else {
        summary.warn("Web assets", "no web UI asset bundle detected");
        summary.suggest("Run frontend build (for source checkout) or reinstall binary package");
    }
}

fn check_auth_profiles(savfox_home: &Path, auto_repair: bool, summary: &mut DoctorSummary) {
    println!();
    println!("{}", "Auth Profiles".bold());
    println!("{}", "-------------".bold());

    let path = savfox_home.join("auth").join("profiles.json");
    if !path.exists() {
        summary.warn("Profiles", &format!("{} (not found)", path.display()));
        summary.suggest("Configure provider profiles or run `savfox login`");
        return;
    }

    let raw = match std::fs::read_to_string(&path) {
        Ok(content) => content,
        Err(err) => {
            summary.fail(
                "Profiles",
                &format!("{} (read error: {err})", path.display()),
            );
            summary.suggest("Fix auth/profiles.json permissions");
            return;
        }
    };

    let mut store: HashMap<String, Vec<StoredAuthProfile>> = match serde_json::from_str(&raw) {
        Ok(parsed) => parsed,
        Err(err) => {
            summary.fail(
                "Profiles",
                &format!("{} (parse error: {err})", path.display()),
            );
            summary.suggest("Repair or remove invalid auth/profiles.json");
            return;
        }
    };

    let mut changed = false;

    for entries in store.values_mut() {
        let before = entries.len();
        entries.retain(|p| !p.id.trim().is_empty() && !p.api_key.trim().is_empty());
        if entries.len() != before {
            changed = true;
        }
    }

    if changed {
        if auto_repair {
            match serde_json::to_string_pretty(&store) {
                Ok(serialized) => {
                    if let Err(err) = std::fs::write(&path, serialized) {
                        summary.fail("Auto-repair", &format!("failed to rewrite profiles: {err}"));
                    } else {
                        summary.ok("Auto-repair", "migrated/cleaned profile store");
                        summary.repaired(format!("rewrote {}", path.display()));
                    }
                }
                Err(err) => {
                    summary.fail("Auto-repair", &format!("serialize failure: {err}"));
                }
            }
        } else {
            summary.warn("Cleanup", "profile migration/cleanup recommended");
            summary.suggest(format!(
                "Run `savfox doctor --yes --savfox-home {}`",
                savfox_home.display()
            ));
        }
    }

    if store.is_empty() {
        summary.warn("Profiles", "no provider profiles configured");
        summary.suggest("Add at least one provider profile");
        return;
    }

    println!(
        "{:<20} {:>5} {:>9} {:>9} {:>9} {:>12}",
        "Provider", "Total", "Ready", "Cooldown", "Failed", "UsageTok"
    );
    println!("{}", "-".repeat(72));
    let now = now_ms();

    let mut providers: Vec<_> = store.into_iter().collect();
    providers.sort_by(|a, b| a.0.cmp(&b.0));
    for (provider, profiles) in providers {
        let mut ready = 0_u32;
        let mut cooldown = 0_u32;
        let mut failed = 0_u32;
        let mut usage_tokens = 0_u64;

        for profile in &profiles {
            usage_tokens = usage_tokens.saturating_add(profile.usage_tokens);
            match profile.cooldown_until {
                Some(PERMANENT_FAILURE_SENTINEL) => failed = failed.saturating_add(1),
                Some(until) if until > now => cooldown = cooldown.saturating_add(1),
                _ => ready = ready.saturating_add(1),
            }
        }

        println!(
            "{:<20} {:>5} {:>9} {:>9} {:>9} {:>12}",
            provider,
            profiles.len(),
            ready,
            cooldown,
            failed,
            usage_tokens
        );

        if ready == 0 {
            summary.warn(
                "Provider health",
                &format!("{provider}: no ready profiles (all cooldown/failed)"),
            );
            summary.suggest(format!(
                "Rotate or replace credentials for provider `{provider}`"
            ));
        } else {
            summary.ok(
                "Provider health",
                &format!("{provider}: {ready} ready profile(s)"),
            );
        }
    }
}

async fn check_network(summary: &mut DoctorSummary) {
    println!();
    println!("{}", "Network".bold());
    println!("{}", "-------".bold());

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(5))
        .build();

    let client = match client {
        Ok(c) => c,
        Err(e) => {
            summary.fail("HTTP client", &format!("failed to create client: {e}"));
            return;
        }
    };

    let url = "https://api.openai.com";
    match client.head(url).send().await {
        Ok(resp) => {
            let status = resp.status();
            if status.is_success() || status.is_redirection() || status == 405 {
                summary.ok("OpenAI API", &format!("{url} reachable (HTTP {status})"));
            } else {
                summary.warn("OpenAI API", &format!("{url} responded with HTTP {status}"));
            }
        }
        Err(e) => {
            if e.is_timeout() {
                summary.fail("OpenAI API", &format!("{url} timed out after 5s"));
            } else if e.is_connect() {
                summary.fail("OpenAI API", &format!("{url} connection refused"));
            } else {
                summary.fail("OpenAI API", &format!("{url} error: {e}"));
            }
        }
    }
}

fn check_disk_space(savfox_home: &Path, summary: &mut DoctorSummary) {
    println!();
    println!("{}", "Disk Space".bold());
    println!("{}", "----------".bold());

    let path_to_check = if savfox_home.exists() {
        savfox_home.to_path_buf()
    } else {
        std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."))
    };

    match fs_available_bytes(&path_to_check) {
        Some(bytes) => {
            let gb = bytes as f64 / (1024.0 * 1024.0 * 1024.0);
            if gb < 1.0 {
                let mb = bytes as f64 / (1024.0 * 1024.0);
                summary.warn(
                    "Available",
                    &format!("{:.1} MB on {}", mb, path_to_check.display()),
                );
                summary.suggest("Free disk space (at least 1GB recommended)");
            } else {
                summary.ok(
                    "Available",
                    &format!("{:.1} GB on {}", gb, path_to_check.display()),
                );
            }
        }
        None => {
            summary.warn("Available", "could not determine free disk space");
        }
    }
}

#[cfg(windows)]
#[allow(unsafe_code)]
fn fs_available_bytes(path: &Path) -> Option<u64> {
    use std::os::windows::ffi::OsStrExt;

    let wide: Vec<u16> = path
        .as_os_str()
        .encode_wide()
        .chain(std::iter::once(0))
        .collect();

    let mut free_bytes_available: u64 = 0;
    let ret = unsafe {
        windows_sys::Win32::Storage::FileSystem::GetDiskFreeSpaceExW(
            wide.as_ptr(),
            &mut free_bytes_available,
            std::ptr::null_mut(),
            std::ptr::null_mut(),
        )
    };
    if ret != 0 {
        Some(free_bytes_available)
    } else {
        None
    }
}

#[cfg(unix)]
#[allow(unsafe_code)]
fn fs_available_bytes(path: &Path) -> Option<u64> {
    use std::ffi::CString;
    use std::os::unix::ffi::OsStrExt;

    let c_path = CString::new(path.as_os_str().as_bytes()).ok()?;
    unsafe {
        let mut stat: libc::statvfs = std::mem::zeroed();
        if libc::statvfs(c_path.as_ptr(), &mut stat) == 0 {
            Some(stat.f_bavail as u64 * stat.f_frsize as u64)
        } else {
            None
        }
    }
}

fn check_sessions(savfox_home: &Path, summary: &mut DoctorSummary) {
    println!();
    println!("{}", "Session Store".bold());
    println!("{}", "-------------".bold());

    let sessions_dir = savfox_home.join("sessions");
    if !sessions_dir.exists() {
        summary.warn(
            "Sessions dir",
            &format!("{} (not created yet)", sessions_dir.display()),
        );
        return;
    }

    let sessions_file = sessions_dir.join("sessions.json");
    if !sessions_file.exists() {
        summary.ok(
            "Sessions dir",
            &format!("{} (no sessions yet)", sessions_dir.display()),
        );
        return;
    }

    match std::fs::read_to_string(&sessions_file) {
        Ok(contents) => match serde_json::from_str::<serde_json::Value>(&contents) {
            Ok(serde_json::Value::Object(map)) => {
                let count = map.len();
                summary.ok(
                    "Sessions file",
                    &format!(
                        "{} ({} session{})",
                        sessions_file.display(),
                        count,
                        if count == 1 { "" } else { "s" }
                    ),
                );
            }
            Ok(_) => {
                summary.ok(
                    "Sessions file",
                    &format!("{} (present)", sessions_file.display()),
                );
            }
            Err(e) => {
                summary.warn(
                    "Sessions file",
                    &format!("{} (parse error: {})", sessions_file.display(), e),
                );
            }
        },
        Err(e) => {
            summary.warn(
                "Sessions file",
                &format!("{} (read error: {})", sessions_file.display(), e),
            );
        }
    }
}

async fn check_gateway(summary: &mut DoctorSummary) {
    println!();
    println!("{}", "Gateway".bold());
    println!("{}", "-------".bold());

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(3))
        .build();

    let client = match client {
        Ok(c) => c,
        Err(e) => {
            summary.fail("Gateway", &format!("failed to create HTTP client: {e}"));
            return;
        }
    };

    let url = "http://localhost:18881/health";
    match client.get(url).send().await {
        Ok(resp) => {
            let status = resp.status();
            if status.is_success() {
                summary.ok(
                    "Gateway",
                    &format!("running at localhost:18881 (HTTP {status})"),
                );
            } else {
                summary.warn(
                    "Gateway",
                    &format!("responded with HTTP {status} at localhost:18881"),
                );
            }
        }
        Err(e) => {
            if e.is_connect() {
                summary.ok(
                    "Gateway",
                    "not running (connect refused at localhost:18881)",
                );
            } else if e.is_timeout() {
                summary.warn("Gateway", "localhost:18881 timed out after 3s");
            } else {
                summary.warn("Gateway", &format!("localhost:18881 error: {e}"));
            }
        }
    }
}

fn completion_paths() -> Vec<PathBuf> {
    let mut paths = Vec::new();
    let Some(home) = dirs::home_dir() else {
        return paths;
    };

    paths.push(home.join(".local/share/bash-completion/completions/savfox"));
    paths.push(home.join(".zsh/completions/_savfox"));
    paths.push(home.join(".config/fish/completions/savfox.fish"));

    #[cfg(windows)]
    {
        paths.push(home.join("Documents/PowerShell/Microsoft.PowerShell_profile.ps1"));
    }

    paths
}

fn path_contains(path_var: &OsStr, target: &Path) -> bool {
    let target_norm = normalize_path(target);
    std::env::split_paths(path_var).any(|entry| normalize_path(&entry) == target_norm)
}

fn normalize_path(path: &Path) -> String {
    #[cfg(windows)]
    {
        path.to_string_lossy()
            .replace('\\', "/")
            .to_ascii_lowercase()
    }
    #[cfg(not(windows))]
    {
        path.to_string_lossy().to_string()
    }
}

fn now_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as u64
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

pub async fn run_doctor(cmd: DoctorCommand) -> anyhow::Result<()> {
    println!("{}", "Savfox Doctor".bold().underline());
    println!("Running diagnostic checks...");

    let savfox_home = match cmd.savfox_home {
        Some(p) => p,
        None => find_savfox_home().unwrap_or_else(|_| {
            dirs::home_dir()
                .unwrap_or_else(|| PathBuf::from("."))
                .join(".savfox")
        }),
    };

    let mut summary = DoctorSummary::default();

    check_build_info(&mut summary);
    check_config_integrity(&savfox_home, cmd.yes, &mut summary);
    check_dependencies(&mut summary);
    check_environment_setup(&savfox_home, &mut summary);
    check_state_dirs(&savfox_home, cmd.yes, &mut summary);
    check_web_ui_assets(&savfox_home, &mut summary);
    check_auth_profiles(&savfox_home, cmd.yes, &mut summary);

    if cmd.network {
        check_network(&mut summary).await;
    }

    check_disk_space(&savfox_home, &mut summary);
    check_sessions(&savfox_home, &mut summary);
    check_gateway(&mut summary).await;

    println!();
    println!("{}", "Summary".bold());
    println!("{}", "-------".bold());
    println!(
        "  {} OK  {} WARN  {} FAIL",
        summary.ok.to_string().green(),
        summary.warn.to_string().yellow(),
        summary.fail.to_string().red()
    );

    if !summary.repaired.is_empty() {
        println!();
        println!("{}", "Auto-repair actions".bold());
        println!("{}", "-------------------".bold());
        for item in &summary.repaired {
            println!("  - {item}");
        }
    }

    if !summary.suggestions.is_empty() {
        println!();
        println!("{}", "Suggested fixes".bold());
        println!("{}", "---------------".bold());
        for suggestion in &summary.suggestions {
            println!("  - {suggestion}");
        }
    }

    println!();
    println!("{}", "Done.".bold());
    Ok(())
}
