// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Turn } from "./Turn";

export type ReviewStartResponse = { turn: Turn, 
/**
 * Identifies the session where the review runs.
 *
 * For inline reviews, this is the original session id.
 * For detached reviews, this is the id of the new review session.
 */
reviewSessionId: string, };
