// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewDelivery } from "./ReviewDelivery";
import type { ReviewTarget } from "./ReviewTarget";

export type ReviewStartParams = { sessionId: string, target: ReviewTarget, 
/**
 * Where to run the review: inline (default) on the current session or
 * detached on a new session (returned in `reviewSessionId`).
 */
delivery: ReviewDelivery | null, };
