// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionTokenUsage } from "./SessionTokenUsage";

export type SessionTokenUsageUpdatedNotification = { sessionId: string, turnId: string, tokenUsage: SessionTokenUsage, };
