// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Session } from "./Session";

export type SessionRollbackResponse = { 
/**
 * The updated session after applying the rollback, with `turns` populated.
 *
 * The SessionItems stored in each Turn are lossy since we explicitly do not
 * persist all agent interactions, such as command executions. This is the same
 * behavior as `session/resume`.
 */
session: Session, };
