// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitInfo } from "./GitInfo";
import type { SessionSource } from "./SessionSource";
import type { Turn } from "./Turn";

export type Session = { id: string, 
/**
 * Usually the first user message in the session, if available.
 */
preview: string, 
/**
 * Model provider used for this session (for example, 'openai').
 */
modelProvider: string, 
/**
 * Unix timestamp (in seconds) when the session was created.
 */
createdAt: number, 
/**
 * Unix timestamp (in seconds) when the session was last updated.
 */
updatedAt: number, 
/**
 * [UNSTABLE] Path to the session on disk.
 */
path: string | null, 
/**
 * Working directory captured for the session.
 */
cwd: string, 
/**
 * Version of the CLI that created the session.
 */
cliVersion: string, 
/**
 * Origin of the session (CLI, VSCode, savfox exec, savfox app-server, etc.).
 */
source: SessionSource, 
/**
 * Optional Git metadata captured when the session was created.
 */
gitInfo: GitInfo | null, 
/**
 * Only populated on `session/resume`, `session/rollback`, `session/fork`, and `session/read`
 * (when `includeTurns` is true) responses.
 * For all other responses and notifications returning a Session,
 * the turns field will be an empty list.
 */
turns: Array<Turn>, };
