// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { AskForApproval } from "./AskForApproval";
import type { SandboxMode } from "./SandboxMode";

/**
 * There are two ways to fork a session:
 * 1. By session_id: load the session from disk by session_id and fork it into a new session.
 * 2. By path: load the session from disk by path and fork it into a new session.
 *
 * If using path, the session_id param will be ignored.
 *
 * Prefer using session_id whenever possible.
 */
export type SessionForkParams = { sessionId: string, 
/**
 * [UNSTABLE] Specify the rollout path to fork from.
 * If specified, the session_id param will be ignored.
 */
path: string | null, 
/**
 * Configuration overrides for the forked session, if any.
 */
model: string | null, modelProvider: string | null, cwd: string | null, approvalPolicy: AskForApproval | null, sandbox: SandboxMode | null, config: { [key in string]?: JsonValue } | null, baseInstructions: string | null, developerInstructions: string | null, };
