// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Personality } from "../Personality";
import type { ResponseItem } from "../ResponseItem";
import type { JsonValue } from "../serde_json/JsonValue";
import type { AskForApproval } from "./AskForApproval";
import type { SandboxMode } from "./SandboxMode";

/**
 * There are three ways to resume a session:
 * 1. By session_id: load the session from disk by session_id and resume it.
 * 2. By history: instantiate the session from memory and resume it.
 * 3. By path: load the session from disk by path and resume it.
 *
 * The precedence is: history > path > session_id.
 * If using history or path, the session_id param will be ignored.
 *
 * Prefer using session_id whenever possible.
 */
export type SessionResumeParams = { sessionId: string, 
/**
 * [UNSTABLE] FOR CODEX CLOUD - DO NOT USE.
 * If specified, the session will be resumed with the provided history
 * instead of loaded from disk.
 */
history: Array<ResponseItem> | null, 
/**
 * [UNSTABLE] Specify the rollout path to resume from.
 * If specified, the session_id param will be ignored.
 */
path: string | null, 
/**
 * Configuration overrides for the resumed session, if any.
 */
model: string | null, modelProvider: string | null, cwd: string | null, approvalPolicy: AskForApproval | null, sandbox: SandboxMode | null, config: { [key in string]?: JsonValue } | null, baseInstructions: string | null, developerInstructions: string | null, personality: Personality | null, };
