[package]
name = "savfox-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
clap = { workspace = true, features = ["derive", "wrap_help"], optional = true }
savfox-core = { workspace = true }
savfox-gateway-shared = { workspace = true }
savfox-lmstudio = { workspace = true }
savfox-ollama = { workspace = true }
savfox-protocol = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
tokio = { workspace = true, features = ["io-std", "io-util", "rt", "sync"], optional = true }
toml = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"], optional = true }

[features]
# Separate feature so that `clap` is not a mandatory dependency.
cli = ["clap", "serde", "serde_json", "tokio", "toml", "tracing", "tracing-subscriber"]
elapsed = []
sandbox_summary = []

[dev-dependencies]
clap = { workspace = true, features = ["derive", "wrap_help"] }
savfox-utils = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
